
services:
  # 1. A ÂNCORA: Memória Física (Postgres + pgvector)
  postgres:
    image: ankane/pgvector:latest
    container_name: postgres_hiperplano
    ports: ["5432:5432"]
    environment:
      POSTGRES_DB: hiperplano_db
      POSTGRES_USER: devildev
      POSTGRES_PASSWORD: password_quantica
    networks: [fenda_sinaptica]

  # 2. O POTENCIAL: Repouso e Telemetria (Redis)
  redis:
    image: redis:alpine
    container_name: redis_frequencia
    ports: ["6379:6379"]
    networks: [fenda_sinaptica]

  # 3. O GOVERNADOR: Motor Quântico (Ruby on Rails)
  motor_quantico:
    build: 
      context: .
      dockerfile: ./motor_quantico/Dockerfile
    container_name: rails_governanca
    volumes:
      - ./motor_quantico:/rails
      - ./data:/rails/data
    ports: ["3000:3000"]
    depends_on: [postgres, redis]
    environment:
      - RAILS_ENV=development
      - DB_HOST=postgres
      - DB_USER=devildev
      - DB_PASSWORD=password_quantica
      - DATABASE_URL=postgres://devildev:password_quantica@postgres:5432/hiperplano_db
    networks: [fenda_sinaptica]

  # 4. O MÚSCULO: Entrega em Alta Performance (Go)
  go_worker:
    build:
      context: .
      dockerfile: ./go-worker/Dockerfile
    container_name: go_entrega
    ports: ["8080:8080"]
    depends_on: [postgres]
    environment:
      - DB_URL=postgres://devildev:password_quantica@postgres:5432/hiperplano_db?sslmode=disable
    networks: [fenda_sinaptica]

  # 5. O ANALISADOR: Especialista de Fase (Python + MXNet)
  python_analyser:
    build:
      context: .
      dockerfile: ./python-analyser/Dockerfile
    container_name: python_expert
    volumes:
      - ./data:/app/data
    networks: [fenda_sinaptica]

  # 6. A FENDA SINÁPTICA: Proxy e Terminador HTTP/2 (Envoy)
  envoy:
    build:
      context: .
      dockerfile: ./envoy/Dockerfile
    container_name: envoy_proxy
    ports:
      - "10000:10000" # Porta da Prova de Conceito (HTTP/2)
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
    depends_on:
      - motor_quantico
      - go_worker
    networks: [fenda_sinaptica]

  # 7. O OBSERVADOR: Auditor de Integridade (Jenkins)
  jenkins:
    build:
      context: .
      dockerfile: ./jenkinsfile/Dockerfile
    container_name: jenkins_auditor
    ports:
      - "8081:8080" # Acesso ao Dashboard do Jenkins
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Jenkins observa o Docker
      - ./jenkins_home:/var/jenkins_home
    networks: [fenda_sinaptica]

networks:
  fenda_sinaptica:
    driver: bridge
