// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: geometria.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GeometriaService_AnalisarEspaco_FullMethodName = "/geometria.GeometriaService/AnalisarEspaco"
)

// GeometriaServiceClient is the client API for GeometriaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// O Serviço de Geometria da Informação
type GeometriaServiceClient interface {
	// Recebe um vetor e retorna a análise de curvatura/massa
	AnalisarEspaco(ctx context.Context, in *VetorInercial, opts ...grpc.CallOption) (*AnaliseInfo, error)
}

type geometriaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGeometriaServiceClient(cc grpc.ClientConnInterface) GeometriaServiceClient {
	return &geometriaServiceClient{cc}
}

func (c *geometriaServiceClient) AnalisarEspaco(ctx context.Context, in *VetorInercial, opts ...grpc.CallOption) (*AnaliseInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnaliseInfo)
	err := c.cc.Invoke(ctx, GeometriaService_AnalisarEspaco_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeometriaServiceServer is the server API for GeometriaService service.
// All implementations must embed UnimplementedGeometriaServiceServer
// for forward compatibility.
//
// O Serviço de Geometria da Informação
type GeometriaServiceServer interface {
	// Recebe um vetor e retorna a análise de curvatura/massa
	AnalisarEspaco(context.Context, *VetorInercial) (*AnaliseInfo, error)
	mustEmbedUnimplementedGeometriaServiceServer()
}

// UnimplementedGeometriaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGeometriaServiceServer struct{}

func (UnimplementedGeometriaServiceServer) AnalisarEspaco(context.Context, *VetorInercial) (*AnaliseInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalisarEspaco not implemented")
}
func (UnimplementedGeometriaServiceServer) mustEmbedUnimplementedGeometriaServiceServer() {}
func (UnimplementedGeometriaServiceServer) testEmbeddedByValue()                          {}

// UnsafeGeometriaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeometriaServiceServer will
// result in compilation errors.
type UnsafeGeometriaServiceServer interface {
	mustEmbedUnimplementedGeometriaServiceServer()
}

func RegisterGeometriaServiceServer(s grpc.ServiceRegistrar, srv GeometriaServiceServer) {
	// If the following call panics, it indicates UnimplementedGeometriaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GeometriaService_ServiceDesc, srv)
}

func _GeometriaService_AnalisarEspaco_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VetorInercial)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeometriaServiceServer).AnalisarEspaco(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeometriaService_AnalisarEspaco_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeometriaServiceServer).AnalisarEspaco(ctx, req.(*VetorInercial))
	}
	return interceptor(ctx, in, info, handler)
}

// GeometriaService_ServiceDesc is the grpc.ServiceDesc for GeometriaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GeometriaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "geometria.GeometriaService",
	HandlerType: (*GeometriaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalisarEspaco",
			Handler:    _GeometriaService_AnalisarEspaco_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "geometria.proto",
}
