// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: geometria.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VetorInercial struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	X             float64                `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	Z             float64                `protobuf:"fixed64,4,opt,name=z,proto3" json:"z,omitempty"`
	Contexto      string                 `protobuf:"bytes,5,opt,name=contexto,proto3" json:"contexto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VetorInercial) Reset() {
	*x = VetorInercial{}
	mi := &file_geometria_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VetorInercial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VetorInercial) ProtoMessage() {}

func (x *VetorInercial) ProtoReflect() protoreflect.Message {
	mi := &file_geometria_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VetorInercial.ProtoReflect.Descriptor instead.
func (*VetorInercial) Descriptor() ([]byte, []int) {
	return file_geometria_proto_rawDescGZIP(), []int{0}
}

func (x *VetorInercial) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VetorInercial) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *VetorInercial) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *VetorInercial) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *VetorInercial) GetContexto() string {
	if x != nil {
		return x.Contexto
	}
	return ""
}

type AnaliseInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Densidade     float64                `protobuf:"fixed64,1,opt,name=densidade,proto3" json:"densidade,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // Importante para testar o Load Balance (quem processou?)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnaliseInfo) Reset() {
	*x = AnaliseInfo{}
	mi := &file_geometria_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnaliseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnaliseInfo) ProtoMessage() {}

func (x *AnaliseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_geometria_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnaliseInfo.ProtoReflect.Descriptor instead.
func (*AnaliseInfo) Descriptor() ([]byte, []int) {
	return file_geometria_proto_rawDescGZIP(), []int{1}
}

func (x *AnaliseInfo) GetDensidade() float64 {
	if x != nil {
		return x.Densidade
	}
	return 0
}

func (x *AnaliseInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AnaliseInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

var File_geometria_proto protoreflect.FileDescriptor

const file_geometria_proto_rawDesc = "" +
	"\n" +
	"\x0fgeometria.proto\x12\tgeometria\"e\n" +
	"\rVetorInercial\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\f\n" +
	"\x01x\x18\x02 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x01R\x01y\x12\f\n" +
	"\x01z\x18\x04 \x01(\x01R\x01z\x12\x1a\n" +
	"\bcontexto\x18\x05 \x01(\tR\bcontexto\"\\\n" +
	"\vAnaliseInfo\x12\x1c\n" +
	"\tdensidade\x18\x01 \x01(\x01R\tdensidade\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId2X\n" +
	"\x10GeometriaService\x12D\n" +
	"\x0eAnalisarEspaco\x12\x18.geometria.VetorInercial\x1a\x16.geometria.AnaliseInfo\"\x00B\x1aZ\x18geometria-info/worker/pbb\x06proto3"

var (
	file_geometria_proto_rawDescOnce sync.Once
	file_geometria_proto_rawDescData []byte
)

func file_geometria_proto_rawDescGZIP() []byte {
	file_geometria_proto_rawDescOnce.Do(func() {
		file_geometria_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_geometria_proto_rawDesc), len(file_geometria_proto_rawDesc)))
	})
	return file_geometria_proto_rawDescData
}

var file_geometria_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_geometria_proto_goTypes = []any{
	(*VetorInercial)(nil), // 0: geometria.VetorInercial
	(*AnaliseInfo)(nil),   // 1: geometria.AnaliseInfo
}
var file_geometria_proto_depIdxs = []int32{
	0, // 0: geometria.GeometriaService.AnalisarEspaco:input_type -> geometria.VetorInercial
	1, // 1: geometria.GeometriaService.AnalisarEspaco:output_type -> geometria.AnaliseInfo
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_geometria_proto_init() }
func file_geometria_proto_init() {
	if File_geometria_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_geometria_proto_rawDesc), len(file_geometria_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_geometria_proto_goTypes,
		DependencyIndexes: file_geometria_proto_depIdxs,
		MessageInfos:      file_geometria_proto_msgTypes,
	}.Build()
	File_geometria_proto = out.File
	file_geometria_proto_goTypes = nil
	file_geometria_proto_depIdxs = nil
}
